version: '3.8'

services:
  backend:
    build: ./backend
    container_name: my-backend
    ports:
      - "5173:5173"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: my-frontend
    ports:
      - "5000:5000"   # フロントエンドが3000番で起動する例（必要に応じて変更）
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge